### PR TITLE
fixed bug #2: not converting facts

### PR DESCRIPTION
**Pull request by 21h**
changed regexp, now facts converting to yaml

### CODE REVIEW

**Comment by dtschan** [comment]
Thank you for opening this issue and pull request. Unfortunately this change breaks the parsing of other values, e.g. quoted values with spaces. I'll look into a fix that doesn't break existing behaviour.

**Comment by 21h** [comment]
Oh, sorry, with spaces there bug

srv0 ansible_host=195.234.33.12 ansible_user=root ansible_ssh_private_key_file="secrets/git.pem"
srv1 ansible_host=15.6.4.185 ansible_user=root ansible_ssh_private_key_file=secrets/git.pem
srv2 ansible_host=18.21.172.29 ansible_user=root ansible_ssh_private_key_file=secrets/git.pem

**Comment by 21h** [comment]
I changed regex to  ([a-zA-Z][a-zA-Z0-9\_]+)=((([a-zA-Z0-9\$\%\@\.\_\-\/\\]+)|([\'\"])([\ a-zA-Z0-9\$\%\@\.\_\-\/\\]+)([\'\"])))

works fine with:
srv0 ansible_host=195.234.33.12 ansible_user=root ansible_ssh_private_key_file='secret s/git.p em' somevar=value
srv1 ansible_host=15.6.4.185 ansible_user=root ansible_ssh_private_key_file=secrets/git.pem
srv2 ansible_host=18.21.172.29 ansible_user=root ansible_ssh_private_key_file=secrets/git.pem

**Comment by dtschan** [comment]
Fixed in 42c7e0a

**Pull request closed without merging**
